# Generated by Django 3.1.5 on 2021-01-14 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_auto_20210114_1327'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='are_selling',
            field=models.BooleanField(default=False, verbose_name='درحال فروش'),
        ),
        migrations.AddField(
            model_name='product',
            name='future',
            field=models.BooleanField(default=False, verbose_name='محصولات آینده'),
        ),
    ]
