# Generated by Django 3.1.5 on 2021-05-28 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_slider'),
    ]

    operations = [
        migrations.AddField(
            model_name='slider',
            name='description',
            field=models.CharField(default=4, max_length=100, verbose_name='توضیحات '),
            preserve_default=False,
        ),
    ]
