# Generated by Django 3.1.5 on 2021-05-28 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_slider_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='slider',
            name='discount',
            field=models.CharField(default=1, max_length=50, verbose_name='تخفیف'),
            preserve_default=False,
        ),
    ]
