# Generated by Django 3.1.5 on 2021-05-28 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_slider_discount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slider',
            name='description',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='توضیحات '),
        ),
        migrations.AlterField(
            model_name='slider',
            name='discount',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='تخفیف'),
        ),
        migrations.AlterField(
            model_name='slider',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='نام '),
        ),
    ]
