# Generated by Django 3.1.5 on 2021-05-28 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20210528_2226'),
    ]

    operations = [
        migrations.AddField(
            model_name='slider',
            name='main_slider',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='slider',
            name='second_slider',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='slider',
            name='third_slider',
            field=models.BooleanField(default=False),
        ),
    ]
